<?php if($this->entry): ?>
	<h4><?php echo $this->entry->name; ?></h4>

	<p><h5>Country:  <?php echo $this->country->name . ' (' . $this->country->code . ')'; ?></h6></p>

	<div id="map"></div>
	<input id="address" type="hidden" value="<?php echo $this->GoogleMap($this->escape($this->entry->name), $this->escape($this->country->name)); ?>">
	
	<script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 8,
          center: {lat: 0, lng: 0}
        });
        var geocoder = new google.maps.Geocoder();

          geocodeAddress(geocoder, map);

      }

      function geocodeAddress(geocoder, resultsMap) {
        var address = document.getElementById('address').value;
        geocoder.geocode({'address': address}, function(results, status) {
          if (status === 'OK') {
            resultsMap.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
              map: resultsMap,
              position: results[0].geometry.location
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC27Iz0B5dWF9LvUGKkFVjej79pzV9q_lI&callback=initMap">
    </script>	
	
<?php else: ?>
	No Record Found	
	
<?php endif; ?>